spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
auth:
  jwt:
    secretKey: ${AUTH_SECRET_KEY}
  accessTokenExpiresInMinutes: 240
  refreshTokenExpiresInMinutes: 480